### PR TITLE
env var to read from package and user env

### PR DESCRIPTION
**Pull request by imda-normanchia**

### CODE REVIEW

**Comment by imda-normanchia** [comment]
`rec_filepath = EnvironmentVars.get_file_dir(EnvVariables.RECIPES, f"{rec_id}.json")`
An example on how to find the file path of the file that you are trying to find.

**Comment by imda-normanchia** [comment]
`EnvironmentVars.get_file_directory(EnvVariables.COOKBOOKS)`

An example on how to get the directory to add the files to.

**Comment by imda-normanchia** [comment]
```
RECIPE directory is ['/Users/normanchia/LocalDocs/TestDir/data/recipes', '/Users/normanchia/LocalDocs/Moonshot2/moonshot/moonshot/data/recipes']
COOKBOOK directory is [None, '/Users/normanchia/LocalDocs/Moonshot2/moonshot/moonshot/data/cookbooks']
RECIPE: arc.json file is at /Users/normanchia/LocalDocs/Moonshot2/moonshot/moonshot/data/recipes/arc.json
RECIPE: bbq.json file is at /Users/normanchia/LocalDocs/TestDir/data/recipes/bbq.json
COOKBOOK: arc.json file is at /Users/normanchia/LocalDocs/Moonshot2/moonshot/moonshot/data/cookbooks/cbbq-amb-cookbook.json
Adding your recipe here /Users/normanchia/LocalDocs/TestDir/data/recipes
Adding your cookbook here /Users/normanchia/LocalDocs/Moonshot2/moonshot/moonshot/data/cookbooks
```

tested with this 2 environment variable. 
Recipes env variable is set and the path defined only contains bbq.json

**Comment by imda-lionelteo** [comment]
merged to ms-143 and updated to work with storage.

**Pull request closed without merging**
